### ISSUE TITLE
Update mrclay/minify version ?

### ISSUE THREAD

**Issue by Nuranto** [Stolz/Assets#101]
Hello,
Could be great to benefit from last fixes of mrclay/minify 3.0.x !

**Comment by Stolz** [comment]
@Nuranto I just updated dependencies to mrclay/minify  ^3.0 in the develop branch. Please try it and let me know if you have any issues:

    composer require stolz/assets:dev-develop

**Comment by Nuranto** [comment]
Hello @Stolz 

There's a fatal error in `Manager` class. `\JSMin` have to become `\JSMin\JSMin`
When that's fixed, it seems OK.

**Comment by Stolz** [comment]
@Nuranto This has been merged into the main branch and released as version `0.2`

**Comment by Nuranto** [comment]
Thanks !
