### ISSUE TITLE
Inline scripts

### ISSUE THREAD

**Issue by fisharebest** [Stolz/Assets#36]
As well as external resources (files), it is often useful to manage inline resouces (scripts) at the same time.

For example, [ZendFramework](http://framework.zend.com/manual/2.0/en/modules/zend.view.helpers.head-script.html) offers this feature via its headScript->appendScript() and headScript->appendFile() methods.  I have coded something similar in many projects.

Translated to stolz/assets, it would look something like this:

```
/* load the libraries */
Asset::addJs('jquery.js');
Asset::addJs('jquery.widget.js');
/* use the libraries */
Asset::addInlineJs('jQuery("#abc").widget();');
```

When you come to render the data, you would get this:

```
<script src="asset-pipeline.js"></script>
<script>jQuery("#abc").widget();</script>
```

We collect the inline scripts, and render them after the external scripts.

Does this sort of feature have a place in this project?

**Comment by erickmonteiro** [comment]
Hello, in laravel 5 where I put the code?

thank you in advance

class Assets extends \Stolz\Assets\Manager {
    protected $inline_js = '';

    public function addInlineJs($js) {
        $this->inline_js .= '<script>' . $js . '</script>';
    }

    public function js($attributes = null) {
        return parent::js($attributes) . $this->inline_js;
    }

    public function resetJs() {
    $this->inline_js = '';
    return parent::resetJs();
    }
}

**Comment by Stolz** [comment]
@erickmonteiro, you can put it anywhere you want as long as the place is listed in your `composer.json` autoload section and you use the right namespace .

Since in L5 the `app` directory is autoloaded with psr-4 you could put it in `app/Assets/` directory and use the `App\Assets` namespace.

If you still want to use the `Assets` facade with your new functionality then you will need to use a [custom service provider](http://laravel.com/docs/master/providers). You can extend the [official one](https://github.com/Stolz/Assets/blob/master/src/Laravel/ServiceProvider.php) and change the 'stolz.assets' binding to return an instance of your class i.e.:

    return new \App\Assets\Manager($app['config']['assets']);

**Comment by judgej** [comment]
Is this something incorporated into the library yet, or do we still need to extend it as shown here? Being able to mix file and URL-based assets with in-line JS is an incredibly usefult feature, and a must-have for my general use (how other's mileage varies, I don't know).

**Comment by hotrush** [comment]
@judgej I do this via View::composer

**Comment by judgej** [comment]
@hotrush what part of the problem does the View::composer solve? It sounds interesting, but so far as I can see, it is a technique that avoids the need to fetch a value in a controller (or a parent view) and explicitly pass it into a view. I'm guessing it is how the `$errors` collection is always available in all views, all the time. Presumably you have something that collects inline JS from various places, and makes it available for binding to some or other view?

**Comment by hotrush** [comment]
@judgej in my case i need to pass some data from php to javascript (but it can be modified as you want).
Here an example:
In my BaseController i have next:
```
/**
 * Data that will be forward to layout as js variables
 * Key => Value array
 * Array to json convert manually
 * @var array
 */
protected $scriptComposer = array();
```
in ```setupLayout()``` method of this controller i have
```
// inject inline script into layout
View::composer('script-composer', function($view) {
    $view->with('scriptComposer', $this->scriptComposer);
});
```
in layout view
```
@include('script-composer')
{{ Assets::js() }}
```
script composer view (it may bind key->value data, but can be modified for your purposes)
```
@if(isset($scriptComposer) && !empty($scriptComposer))
<script type="text/javascript">
    @foreach($scriptComposer as $key=>$value)
        var {{ $key }} = {{ $value }};
    @endforeach
</script>
@endif
```
and in controllers method i do next
```
$this->scriptComposer['userID'] = 123;
```

**Comment by judgej** [comment]
Thanks, that makes sense. So here the controllers throw together key/value data, and the View::composer is used to make sure that key/value data is available to any JS running on the page. Your static JS assets then know what data to look for, and how to use it.

I think I would want to pass in fragments of JS too - more than just variables - and some of those fragments would come from sub-views within the page, but this would certainly work for that too.

**Comment by Nuranto** [comment]
+1

With a little modification : 


Translated to stolz/assets, it would look something like this:
```
/* load the libraries */
Asset::addJs('jquery.js');
Asset::addJs('jquery.widget.js');
/* use the libraries */
Asset::addInlineJs('jQuery("#abc").widget();');
```
When you come to render the data, you would get this:
```
<script src="asset-pipeline.js"></script>
```
with `<script>jQuery("#abc").widget();</script>` at the end of `asset-pipeline.js` file

**Comment by Stolz** [comment]
@Nuranto please take a look at Laravel Blade stacks. They allow you to accomplish the inline assets feature very easily.

https://laravel.com/docs/5.6/blade#stacks
