### ISSUE TITLE
Please add support for two pipelines (one for css, one for js) and exceptions

### ISSUE THREAD

**Issue by vladrusu** [Stolz/Assets#37]
First, thank you for your plugin, it is very good and I use it for my most recent project.

I would like to have support for two different pipelines, one for CSS and one for JS.
I happen to modify the css without touching the JS files ...
When I increment the pipeline, the JS minified file is recreated.... and I don't like it.

Also, the ->reset->addJs/css trick is cumbersome for a plugin that aims to do it easy... and yells for some more flexible config, eventually.

I would like to have support for exceptions (i.e. files that are NOT minfied and inserted as they are...) in config.
For example I use Google maps v3 JS api.

If I add it in a collection in config.php, it will not work, simply because the library is not working LOCALLY (unlike jQuery, bootstrap etc), and must be on the Google servers.

```
    'googlemaps' => [
        ['http://maps.googleapis.com/maps/api/js?v=3.exp', insert_as_it_is => true] //// I WOULD LOVE TO CAN BE ABLE TO DO THS
```

In  this case, Assets::js(), should output ideally both the google maps script _NOT MINIFIED, PIPELINED_ and the rest of the scripts, pipelined.

Thank you once again!

**Comment by Stolz** [comment]
Please note last update has introduced the [multitenancy](https://github.com/Stolz/Assets/tree/master#multitenancy) feature of the library, which may help you in that scenario.
