### ISSUE TITLE
CSS files containing url(...) - rewrite path for pipeline?

### ISSUE THREAD

**Issue by fisharebest** [Stolz/Assets#38]
Suppose I have a CSS file `/css/style.css`, which contains a rule such as `#id { background-image: url(img.png); }` and I use the pipeline option.

My pipeline file (e.g. `/min/7c358b3d092429876a4fb752721bfca8.css`) still contains the exact same rule `#id { background-image: url(img.png); }`.  However this doesn't work, because `img.png` is in the `css` folder and not the `min` folder.

The pipeline file needs to contain `#id { background-image: url(../css/img.png); }`.

The Minify_CSS library seems to have an option to rewrite URLs like this (`prependRelativePath`), but I can't work out how to configure/enable it.  Am I missing something obvious?

**Comment by lbausch** [comment]
I used [Assetic](https://github.com/kriswallsmith/assetic) to do the rewrite stuff. This way I don't have to mess around with RegEx and can rely on battle-tested solutions. Anyway I'm sure the following snippet can be improved:

```php
'fetch_command' => function ($asset) {    
    $content = file_get_contents($asset);
                        
    $info = pathinfo($asset);
                   
    $sourceRoot = 'assets/'. $info['extension'];
    $sourcePath = $info['extension'] . DIRECTORY_SEPARATOR . $info['basename'];

    $rewrite = new Assetic\Filter\CssRewriteFilter();            
    $assetic = new Assetic\Asset\StringAsset($content, [$rewrite], $sourceRoot, $sourcePath);
    $assetic->setTargetPath('assets/min');
            
    return $assetic->dump();
},
```
