### ISSUE TITLE
How to pipeline only certain collections

### ISSUE THREAD

**Issue by nathanfirth** [Stolz/Assets#40]
What I'm trying to do is have a collection of base JS & CSS that gets included via the autoload assets array. I want this "base" collection to get pipelined. Then as I manually add javascript via Asset::add() for specific pages, that should not get pipelined into the main file. It could get pipelined into a separate file specific files as long as it's independent of the main base collection. Is this possible?

**Comment by Stolz** [comment]
Please note last update has introduced the [multitenancy](https://github.com/Stolz/Assets/tree/master#multitenancy) feature of the library, which it may help you in that scenario.
