### ISSUE TITLE
Serving Pipelined Asset through CDN

### ISSUE THREAD

**Issue by mrgauthier** [Stolz/Assets#51]
I see that there's some debate on relative / absolute linking to the generated asset links using this package.  For the most part I don't really take a side one way or the other.  The \<base\> tag allows you to get away with handling assets relative to the root URI of your application from subdirectories without much issue.

HOWEVER...  I feel like if there was a config variable to specify whether or not there is to be some sort of prefix path to the relative link paths we could easily supply a CDN path for our Assets that are generated via Pipelines.   Any thoughts on that?

**Comment by Stolz** [comment]
To make it work to have to copy your assets to your CDN and the update your config to point to your CDN address. Were you talking about something different such the library copying the assets to your CDN server automatically?

**Comment by Stolz** [comment]
@mrgauthier , please take a look at the [notify_command](https://github.com/Stolz/Assets/blob/master/API.md#notify_command) configuration option.

It accepts a closure that will be invoked every time new assets are pipelined. You can use it to hook to pipeline and upload your new assets to your CDN. Then you can load your CDN assets using their absolute URL.

**Comment by Stolz** [comment]
Please note last update has introduced the [multitenancy](https://github.com/Stolz/Assets/tree/master#multitenancy) feature of the library, which it may help you in that scenario.
