### ISSUE TITLE
Remove Query String From Static Resources?

### ISSUE THREAD

**Issue by rajivseelam** [Stolz/Assets#52]
According to this article (and some other resources)

http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

In pipeline function we add query at the end of the path `$timestamp = (intval($this->pipeline) > 1) ? '?' . $this->pipeline : null;`

If we add `$timestamp` just before `$extension` this can be easily solved. Let me know what you think, I would be happy to send a pull request.

**Comment by Stolz** [comment]
The commit has been merged into develop branch already. If you use that branch feel free to remove the helper
