### ISSUE TITLE
Laravel 5 - Does Assets::add() Still Work?

### ISSUE THREAD

**Issue by beardedbrew** [Stolz/Assets#54]
Referencing Assets::add() in a controller returns the following error in L5.
Class 'App\Http\Controllers\Assets' not found

**Comment by beardedbrew** [comment]
Actually calling
\Assets::add();
fixed the issue.

**Comment by Stolz** [comment]
@beardedbrew Larave 5 introduces namespaces for controllers so you should use `\Assets::add()`, or simply add `use Assets` after the declaration of your controller namespace.
