### ISSUE TITLE
Laravel 5 and php artisan asset:flush => incorrect path

### ISSUE THREAD

**Issue by lbausch** [Stolz/Assets#59]
When running `php artisan asset:flush` in an Laravel 5 installation the commands like
```php
$pipeDir = Config::get('assets::pipeline_dir', 'min');
Config::get('assets::css_dir', 'css')
Config::get('assets::js_dir', 'js')
```
always use the given default value ("min") and flush will fail (wrong directories get cleared).

**Comment by Stolz** [comment]
@lbausch thanks for reporting. It's been fixed in the latest version, please update.

**Comment by lbausch** [comment]
Thank you very much for fixing this issue so fast :) Works like a charm.
