### ISSUE TITLE
Can't get this to install.

### ISSUE THREAD

**Issue by Coreinsanity** [Stolz/Assets#60]
As per the instructions, I've executed:

```
composer require stolz/assets
```

However, when 

```
'Stolz\Assets\Laravel\ServiceProvider',
```

Exists within the providers array, I get this when doing composer update/install:

```
generating autoload files

"type": Symfony\\Component\\Debug\\Exception\\FatalErrorException

"message": Call to undefined method Stolz\\Assets\\Laravel\\ServiceProvider::mergeConfigFrom()

"file": vendor\\stolz\\assets\\src\\Laravel\\ServiceProvider.php (line 17)

Script php artisan clear-compiled handling the post-update-cmd event returned with an error
```

(cleaned it up some out of the just plain json it provides.)

Any help would be appreciated, I'm using Laravel 4.2

**Comment by Stolz** [comment]
@Coreinsanity, please read [previous issue](https://github.com/Stolz/Assets/issues/55#issuecomment-73024822) for instructions for Laravel 4

**Comment by Coreinsanity** [comment]
I actually had just found that, having a look now, thanks!

Also, you should really note this in the readme lol (at least I don't think I missed it). I initially checked issues on here but never saw that come up (open ones only, I guess)
