### ISSUE TITLE
min php version not 5.3

### ISSUE THREAD

**Issue by anedisi** [Stolz/Assets#62]
There is a new array syntax in service provider and flush pipeline that make it not working on php 5.3.
After replacing the syntax it works again.

There are some suckers that have to work with 5.3 and it would be cool to keep it compatible with 5.3

Thx.

**Comment by Stolz** [comment]
The service provider is meant to be used with Laravel. [Laravel requires PHP >= 5.4](http://laravel.com/docs/5.0#server-requirements). According to PHP_CodeSniffer the assets library itself is 100% compatible with ancient PHP 5.3

**Comment by anedisi** [comment]
Im using the LegacyServiceProvider and there is only one line of code making it not work on 5.3 (laravel 4.1)
