### ISSUE TITLE
php artisan vendor:publish not working

### ISSUE THREAD

**Issue by rajivseelam** [Stolz/Assets#66]
Hi,

This is the first time I am using this package with Laravel 5. When I run the `vendor:publish` command, it doesn't add `assets.php` to config folder.

**Comment by rajivseelam** [comment]
It seems like ServiceProvider is not registered.

**Comment by rajivseelam** [comment]
It is a problem with Laravel 5.

**Comment by photonite** [comment]
why is this issue closed?

**Comment by rajivseelam** [comment]
Hi,

The issue was not with Stolz/Assets package. It was something to do with Laravel 5, which I don't remember now. I've closed the issue as soon as I realized it.
