### ISSUE TITLE
Header and Footer JS / CSS

### ISSUE THREAD

**Issue by superdummy** [Stolz/Assets#76]
Hello, 

first of all, great package, absolutely love it! Thanks for developing it!

I have a small feature request: I think it is very common to have JS script in the footer as well as in the header. So it would be great if there is an option, that allows to specify where to queue the file (header vs footer and even other places...) and then being able to also echo only the specific tagged Assets with Assets::js('my-footer-tag');

I hope this makes sense to you and this feature would make your library even more awesome. 

Thanks

**Comment by Stolz** [comment]
@superdummy you can easily archive it by using multiple instances of the library. Take a look [here](https://github.com/Stolz/Assets/issues/37#issuecomment-57676554)

**Comment by spescina** [comment]
is this feature available in a no-laravel app?
