### ISSUE TITLE
CDN support

### ISSUE THREAD

**Issue by almamundinajpuri** [Stolz/Assets#78]
Hello,
I use this package in most of my laravel apps. Could you pls give me some hint how I can use CDN with the files compressed by this pkg?
Would be great if you had config options to integrate (maybe other) cdn packages.

Regards

**Comment by Stolz** [comment]
Please take a look at the [notify_command](https://github.com/Stolz/Assets/blob/master/API.md#notify_command) configuration option.

It accepts a closure that will be invoked every time new assets are pipelined. You can use it to hook to pipeline and upload your new assets to your CDN. Then you can load your CDN assets using their absolute URL.
