### ISSUE TITLE
Fully qualified url support

### ISSUE THREAD

**Issue by pawelzny** [Stolz/Assets#80]
Hi, 
Can You add support for fully qualified url (absolute) to assets instead of relative path?
Relative paths do not work properly in Laravel.

Thank you in advance.

**Comment by Stolz** [comment]
The library already supports fully qualified url assets. Just add them as you'll normaly do with relative assets. i.e:

    Assets::add('http://example.com/style.css');

BTW, me and some other hundreds of people are using relative assets with Laravel without problems. May be is you describe your scenario we can help.

**Comment by pawelzny** [comment]
I use collections like that:
```
// Twitter Bootstrap
'bootstrap' => array(
	'jquery-cdn',
	'bootstrap.min.css',
	'bootstrap.min.js',
	'npm.js'
),
'autoload' => array('bootstrap'),
```
and then i print my assets with:
```
{!! Assets::css() !!}
{!! Assets::js() !!}
```

in output i got relative path to my assets:
```
<link href="css/min/7ab0b89032c5df8f4b062ab2cd9bf33f.css" type="text/css" rel="stylesheet" />
```
When i go to subpage my browser is searching for assets on path: **`subpage/css/min/7ab0b89032c5df8f4b062ab2cd9bf33f.css`**

It should print fully qualified url i.e: **`http://localhost/css/min/7ab0b89032c5df8f4b062ab2cd9bf33f.css`**

**Comment by Stolz** [comment]
@pawelzny please read the [F.A.Q](https://github.com/Stolz/Assets#why-assets-work-for-the-main-page-but-not-for-subpages)
