### ISSUE TITLE
'php artisan asset:flush' doesn't support multitenancy feature

### ISSUE THREAD

**Issue by RuslanGetmansky** [Stolz/Assets#82]
```FlushPipelineCommand::fire()``` tries to take pipeline_dir, css_dir and js_dir from config without taking in account groups here:
https://github.com/Stolz/Assets/blob/master/src/Laravel/FlushPipelineCommand.php#L35

**Comment by Stolz** [comment]
@RuslanGetmansky , thanks for reporting the problem. It is fixed now.
