### ISSUE TITLE
Class stolz.assets.group.default does not exist 

### ISSUE THREAD

**Issue by eleftrik** [Stolz/Assets#83]
Today, after running `composer update`, I got this exception:

Class stolz.assets.group.default does not exist 

in ..../vendor/laravel/framework/src/Illuminate/Container/Container.php

I'm using Laravel 4.2.18, with LegacyServiceProvider. I think this error has been running since commit d3ebca4a8343b38a6b9640ea41b49546d15f47a3

I temporarily fixed updating my composer.json this way:

`"stolz/assets": "dev-master#6c1a4c264567b23be5b7821c7a72ad4108f870e3",`

Thank you

**Comment by Stolz** [comment]
@eleftrik , it should be fixed now

**Comment by eleftrik** [comment]
Hi @Stolz, I'll try as soon as possible. Thank you so much!
