### ISSUE TITLE
config option to skip  cdn/external  in the pipeline

### ISSUE THREAD

**Issue by zofe** [Stolz/Assets#9]
Great package, 
It will be nice if  a config option can be used to skip  cdn/external from the pipeline (in my case font-awesome wont work pipelined), or if a method can be invoked runtime like:

```
  {{ Assets::reset()->add('jquery-cdn')->js() }}
  {{ Assets::reset()->add(array('custom.js', 'main.js'))->pipeline()->js() }}
```

**Comment by Stolz** [comment]
Please note last update has introduced the [multitenancy](https://github.com/Stolz/Assets/tree/master#multitenancy) feature of the library, which may help you in that scenario.

**Comment by zofe** [comment]
nice, thanks
