### ISSUE TITLE
Why don't use full URLs intead of relatives?

### ISSUE THREAD

**Issue by fede91it** [Stolz/Assets#91]
I always have a lot of problem configuring this library due it generate relative URLs instead of full ones.

Why don't add an option to set if Stolz will generate relative or full urls?

**Comment by Stolz** [comment]
Well, the library generates the kind of URLs you give to it. If you give relative URLs, it will generate relative URLs and if you give absolute URLs, you'll get absolute URL.

The default configuration is for using relative URLs but it can be changed. Why default to relative URLs configuration? 

- To save space and take advantage of hierarchical locality,
- To avoid nightmares when deploying to multiple environment.
- And for [a ton more of reasons](http://stackoverflow.com/questions/2005079/absolute-vs-relative-urls) every web programmer with experience should know.

If you want to to use absolute URLs by default you have many options:
- Always provide absolute URLs.
- Include your base URL in the `css_dir` and `js_dir` options:

	// config.php
	'css_dir' => 'http://mydomain.com/css',
	'js_dir' => 'http://mydomain.com/js',

- Set use the [`<base>` HTML tag](http://www.w3.org/TR/html4/struct/links.html#h-12.4) pointing to your root  base absolute URL.
- Use the `closure` feature of the [css](https://github.com/Stolz/Assets/blob/master/API.md#css-1) and [js](https://github.com/Stolz/Assets/blob/master/API.md#js-1) functions to convert the URLs to your needs

If you have problems configuring and using the relative links, here are two good documents to read:
- http://www.w3.org/TR/html401/struct/links.html#h-12.4.1 (including the links to the RCFs)
- http://tools.ietf.org/html/rfc3986#section-4

**Comment by fede91it** [comment]
When I declare css_dir and js_dir as an url, I get this error:

ErrorException in Manager.php line 464:
mkdir(): Invalid argument (View: D:\Progetti\studioelps.com\StudioElps\resources\views\master.blade.php) (View: D:\Progetti\studioelps.com\StudioElps\resources\views\master.blade.php)

**Comment by fede91it** [comment]
Using absolute URLs work, but causes a mkdir error when pipeline is enabled

**Comment by Stolz** [comment]
@fede91it , sorry for the late response.

I forgot the pipeline uses 'css_dir' and 'js_dir' for creating the dir. Then I'm afraid if you want to default to absolute URL you need to use one of the above approaches.

**Comment by fede91it** [comment]
Ok thanks, I'll send you a PR for this issue asap
