### ISSUE TITLE
S3 Support

### ISSUE THREAD

**Issue by sujitrulz** [Stolz/Assets#94]
Hi @Stolz, 
Is it possible to add files to s3 and fetch the file directly from s3 in blade file?

**Comment by Stolz** [comment]
If you are using the pipeline in theory it would be possible to retrieve the files from S3. If you take a look at the [docs](https://github.com/Stolz/Assets/blob/master/API.md#fetch_command) you'll see there is the `fetch_command` config option which accepts a closure that receives as first parameter the path of the asset to be pipelined. Simply add the logic for fetching files from S3 into that closure and make sure it returns the content of the asset.

For instance, assuming your Laravel S3 disk is properly configured:

``` php
// File: config/assets.php
return [
    /*...*/
    'fetch_command' = function ($asset) {
        return \Storage::disk('s3')->get($asset);
    },
    /*...*/
];
```
