### ISSUE TITLE
Load all assets from a directory

### ISSUE THREAD

**Issue by dinajpuri** [Stolz/Assets#97]
Hello,

Is there a way to load all css, js files from a directory/subdirectory?

Regards
Almamun

**Comment by mikerockett** [comment]
You could always use a directory iterator / glob to build the array yourself. Not a terrible idea to include it in the package, I'd think... Or perhaps some wildcards are in order? I think the only issue with this, however, is determining the correct order in which assets should be loaded. So, if a feature like this is implemented, it would need to give fair warning in terms of that.

**Comment by Stolz** [comment]
You can use the "addDir" function to add all assets matching a pattern within a directory.

https://github.com/Stolz/Assets/blob/master/API.md#adddir

**Comment by mikerockett** [comment]
Ah, didn't see that. 👍
