### ISSUE TITLE
files and URL's with special characters won't load

### ISSUE THREAD

**Issue by ishigami** [Stolz/Assets#99]
Hi Stolz,

First of all, thank you for this package.

And I've found an issue when you add some urls or files with special charactes like ? or # it just won't load these references.

Some examples
```
// config/assets.php
...
	'addthis' => [
		'//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-598f3cabac30c0b2',
	],
	'c7-base' => [
		'main.js?v=' . config('app.version'),
		'c7-front.js?v=' . config('app.version'),
	],
	'gmaps' => [
		'//maps.googleapis.com/maps/api/js?key=' . config('google_api_key') . '&libraries=places&language=en',
		'gmaps/markerclusterer.js',
		'gmaps/gmaps.min.js',
	],
...
```
Tks again.

**Comment by cheycron** [comment]
Adding a &ext=.js to the url solved this issue.  Like _'//maps.googleapis.com/maps/api/js?key=' . config('google_api_key') . '&libraries=places&language=en&ext=.js'_
